# Generated by Django 6.0.3 on 2026-04-18 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20)),
                ('subject_description', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=200)),
                ('semester', models.CharField(blank=True, max_length=20, null=True)),
                ('school_year', models.CharField(blank=True, max_length=20, null=True)),
                ('student_type', models.CharField(blank=True, max_length=50, null=True)),
                ('day', models.CharField(max_length=20)),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('room', models.CharField(max_length=50)),
                ('program', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=100)),
                ('class_size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'unique_together': {('subject_code', 'section', 'semester', 'school_year', 'day', 'time_from', 'time_to')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('dropped', 'Dropped')], default='enrolled', max_length=20)),
                ('absence_count', models.IntegerField(default=0)),
                ('enrolled_date', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classes.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'class_obj')},
            },
        ),
    ]
