# Generated by Django 6.0.4 on 2026-04-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCS', '0003_user_student_id_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('student', 'Student')], max_length=10),
        ),
    ]
