# Generated by Django 6.0.4 on 2026-04-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCS', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
